# Include CI/CD Template for Ansible Roles
include:
  - project: 'rstumpner/ansible-role-template'
    ref: 'master'
    file: '/.gitlab-ci.yml'
# remote cicd template
#   remote: 'https://gitlab.com/rstumpner/ansible-role-template/raw/master/.gitlab-ci.yml'




## disable testing with molecule and docker (actual big mess with ansible molecule docker collections and all)
testing-with-molecule:
  stage: prepare
  artifacts:
    when: always
    paths:
      - tests/
  before_script:
    - apt-get update -qq
    - apt install --no-install-recommends -y python3 python3-dev software-properties-common libapt-pkg-dev git curl vim iputils-ping mtr dnsutils rsync tree python3-pip python3-apt python3-docker python-pip build-essential python-dev
    - apt-add-repository ppa:ansible/ansible
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/trusted.gpg.d/docker-ce.asc
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    - apt update
    - apt install -y ansible python3-markupsafe python3-ecdsa libyaml-0-2 python3-jinja2 python3-yaml python3-paramiko python3-httplib2 python-crypto sshpass docker-ce
    - python -V
    - pip install virtualenv==20.6.0
    - virtualenv --python 3 --system-site-packages virtenv
    - source virtenv/bin/activate
    - pip3 install setuptools ansible==2.9.23 molecule molecule-docker docker apt-wrapper pyvmomi
    - ansible --version
    - docker --version
    - molecule --version
    - docker info
  script:
#    - docker info
    - 'molecule list'
