# Include CI/CD Template for Ansible Roles
include:
  - project: 'rstumpner/ansible-role-template'
    ref: 'master'
    file: '/.gitlab-ci.yml'
# remote cicd template
#   remote: 'https://gitlab.com/rstumpner/ansible-role-template/raw/master/.gitlab-ci.yml'