---
# All Tasks to document the Application
# tenants
# services
# user access
# tags: 
#   - doc

- name: create a directory for live documentation
  delegate_to: localhost
  tags: 
    - doc
    - build
  file: path=./{{ vm_repman_output_dir }}/{{ role_name|basename }}/ state=directory


- name: Generate documentation for the services
  delegate_to: localhost
  tags: 
    - doc
    - build
  template:
    src: doc-default.j2 
    dest: ./{{ vm_repman_output_dir }}/{{ role_name|basename }}/{{ inventory_hostname }}-{{ role_name|basename }}-all.md

- name: Generate markdown documentation for the services
  delegate_to: localhost
  tags: 
    - doc
    - build
  template:
    src: doc-markdown.j2 
    dest: ./{{ vm_repman_output_dir }}/{{ role_name|basename }}/{{ inventory_hostname }}-{{ role_name|basename }}.md

- name: Generate csv documentation for the services
  delegate_to: localhost
  tags: 
    - doc
    - build
  template:
    src: doc-csv.j2 
    dest: ./{{ vm_repman_output_dir }}/{{ role_name|basename }}/{{ inventory_hostname }}-{{ role_name|basename }}.csv