---

# Start the Virtual Machine fhooelibrenms on Ansible 2.5
#- name: Start the Virtual Machine fhooelibrenms
#  tags: vmwareguest-start
#  delegate_to: localhost
#  vmware_guest_powerstate:
#    hostname: "{{ vcenter_hostname }}"
#    username: "{{ vcenter_user }}"
#    password: "{{ vcenter_pass }}"
#    validate_certs: no
#    folder: /Kunden
#    name: "{{ inventory_hostname }}"
#    state: powered-on
#  when: 
#    - not ansible_check_mode
#    - vm_facts.virtual_machines.fhooelibrenms2.power_state == "poweredOff"
#  register: vmdeploy

# Find the Virtual Machine
- name: Find the Virtual Machine on VMware CLuster
  tags: 
     - vmware-find
     - deploy
     - test
     - integration
  ignore_errors: yes
#  connection: local
  delegate_to: localhost
  vmware_guest_find:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    datacenter: "{{ vm_dc }}"
    validate_certs: false
    name: "{{ inventory_hostname }}"
  register: vmfound
  check_mode: no


- name: Print Debug VM Search
  tags:
     - debug
     - test
     - integration
  debug: msg="{{ vmfound }}"


# Get Facts of VM
- name: Get Facts from VMware vSphere for Virtual Machine
  tags: 
     - vmwareguest-facts
     - deploy
     - test
     - integration
  delegate_to: localhost
  vmware_guest_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    datacenter: "{{ vm_dc }}"
    validate_certs: no
    folder: '{{ vm_dc }}/{{ vmfound.folders[0] }}'
    name: "{{ inventory_hostname }}"
  when: 
  - vmfound.failed == false
  register: vm_facts
  check_mode: yes

- name: Print Debug VM Facts
  tags:
     - debug
     - test
     - integration
  debug: msg="{{ vm_facts }}"


# Start the Virtual Machine
- name: Start the Virtual Machine with VMware vSphere
  tags: 
     - vmwareguest-start
     - deploy
  delegate_to: localhost
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    validate_certs: no
    datacenter: "{{ vm_dc }}"
    folder: '{{ vm_dc }}/{{ vmfound.folders[0] }}'
    name: "{{ inventory_hostname }}"
    state: poweredon
    wait_for_ip_address: yes
  when: 
    - not ansible_check_mode
    - vmfound.failed == false
  register: vmdeploy

- name: Print Debug VM Start
  tags:
     - debug
     - deploy
  debug: msg="{{ vmdeploy }}"


# Create a VM from Ubuntu 16.04 Template
- name: Create VM from a template with Vmware vSphere
  tags: 
     - vmwareguest-clone
     - deploy
  delegate_to: localhost
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    validate_certs: no
    folder: 'vm/{{ vm_folder }}'
    cluster: "{{ vm_cluster }}"
    datacenter: "{{ vm_dc }}"
    name: "{{ inventory_hostname }}"
    template: "{{ vm_template }}"
    networks:
    - name: "{{ vm_network }}"
    state: poweredon
    annotation: "Created by Ansible from Template"  
  when: 
    - not ansible_check_mode
    - vmfound.failed == true
    - vm_create == true
  register: vmdeploy
#    wait_for_ip_address: yes
#  register: deployvm

- name: Print Debug VM Clone
  tags:
     - debug
     - deploy
  debug: msg="{{ vmdeploy }}"

# Get Facts of VM
- name: Get Facts from Vmware vSphere for Virtual Machine
  tags: 
     - vmwareguest-facts
     - debug
     - test
     - integration
  delegate_to: localhost
  vmware_guest_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    datacenter: "{{ vm_dc }}"
    validate_certs: no
    folder: '{{ vm_dc }}/{{ vmfound.folders[0] }}'
    name: "{{ inventory_hostname }}"
  when: 
  - vmfound.failed == false
  register: vm_facts

- name: Print Debug VM Facts
  tags:
     - debug
     - test
     - integration
  debug: msg="{{ vm_facts }}"
  
# Set Facts from vmware
- name: Set Facts from Vcenter with ipv6 Error
  tags:
     - deploy
  ignore_errors: yes
  set_fact:
    delegate_facts: true
    delegate_to: "{{ inventory_hostname }}"
    ansible_default_ipv4: "{{ vm_facts.instance.hw_eth0.ipaddresses[0] }}"
    ansible_host: "{{ vm_facts.instance.hw_eth0.ipaddresses[0] }}"
  when: 
    - not ansible_check_mode
    - vm_facts.instance.ipv4
    - vm_facts.instance.ipv4.find(":") != -1

- name: Set Facts from Vcenter with ipv4 Adress
  tags:
     - deploy
  ignore_errors: yes
  set_fact:
    delegate_facts: true
    delegate_to: "{{ inventory_hostname }}"
    ansible_default_ipv4: "{{ vm_facts.instance.ipv4 }}"
    ansible_host: "{{ vm_facts.instance.ipv4 }}"
  when: 
    - not ansible_check_mode
    - vm_facts.instance.ipv4
    - vm_facts.instance.ipv4.find(".") != -1