---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: run apt-get update and install python
      raw: "{{ item }}"
      loop:
        - apt-get update
        - apt-get -y install python3
#      become: true
#  tasks:
#    - name: Install python3
#      apt: 
#        name: ['python3']
#        state: installed 
#      when: ansible_os_family == "Debian"

